### ISSUE TITLE
Release error when no --file argument supplied in the CLI

### ISSUE THREAD

**Issue by bmiles** [transcriptic/runner#9]
Hey, giving the release branch a play.

I get this error:

``` python
➜  protocols git:(provision_fix) ✗ transcriptic release "package-id"                                 
Traceback (most recent call last):
  File "/Users/Ben/anaconda/bin/transcriptic", line 9, in <module>
    load_entry_point('transcriptic==1.2.0', 'console_scripts', 'transcriptic')()
  File "/Users/Ben/anaconda/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Ben/anaconda/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/Users/Ben/anaconda/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Ben/anaconda/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Ben/anaconda/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "build/bdist.macosx-10.5-x86_64/egg/transcriptic.py", line 198, in release
    @click.argument('protocol_name')
  File "build/bdist.macosx-10.5-x86_64/egg/transcriptic.py", line 157, in upload
    click.echo('Creating empty manifest.json...')
  File "/Users/Ben/anaconda/lib/python2.7/posixpath.py", line 121, in basename
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

However if I provide the name of an existing archive via the --file argument.

It zips up all the files and uploads the most recent version, however the actual specified existing archive uploads with an error. So below an archive called `release_v1.5.2.zip` was created and uploaded just fine

``` bash
transcriptic release "package-id" -f release_1.5.1.zip
Creating archive with all files within this directory...
Uploading to package with id package-id
Validating package...
Package uploaded successfully! Visit https://secure.transcriptic.com/ellis_lab/packages/package-id to publish.
```

Sorry I would try and fix it if my python was a little better!

**Comment by therzka** [comment]
Thanks Ben! This is still a WIP, I'm actually going to be splitting up the upload and release functions later.  I'll deal with this bug too :)

**Comment by bmiles** [comment]
You're welcome, I really like it.

Sounds great :)

**Comment by therzka** [comment]
I just made a ton of updates to this branch and outlined instructions in the README, check it out!
